name: a2_to_do_list
description: A new Flutter project for  TODO list.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
#  assets:
#    - images/